// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_C-LwLuZDZksBDr4SlUAg_D7SSNvxCU',
    appId: '1:480511478888:web:20fff097eb158bc6b03fdd',
    messagingSenderId: '480511478888',
    projectId: 'allynd-app',
    authDomain: 'allynd-app.firebaseapp.com',
    storageBucket: 'allynd-app.appspot.com',
    measurementId: 'G-28C8CG2DVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4YN03l0PQzKd0IEpxeataLaudVRmB2Q',
    appId: '1:480511478888:android:3ce82577a6f2e396b03fdd',
    messagingSenderId: '480511478888',
    projectId: 'allynd-app',
    storageBucket: 'allynd-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiuPL1cK5VPqPQd0ExilJHtw9NVhQVF10',
    appId: '1:480511478888:ios:b1207ce54f838f7ab03fdd',
    messagingSenderId: '480511478888',
    projectId: 'allynd-app',
    storageBucket: 'allynd-app.appspot.com',
    iosClientId: '480511478888-i2blccfotc0qbas5lrulds6p44vacm83.apps.googleusercontent.com',
    iosBundleId: 'tech.allyned.allyned',
  );
}
